name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy using Token
        run: firebase deploy --only hosting --site impacto-animal-30043559-620c9 --project impacto-animal-30043559-620c9 --token "${{ secrets.FIREBASE_TOKEN }}"
